/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relojalarma;

import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author serxa
 */
public class Interfaz extends javax.swing.JFrame {
    static boolean reloj_alarma=true;  //True=Reloj  False=Alarma

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setVisible(true);
        Font fuente = new Font("Dialog", Font.BOLD, 60);
        Visualizador.setFont(fuente);
        Visualizador.setHorizontalAlignment(JTextField.CENTER);
        TFmostrar.setText("Reloj");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFmostrar = new javax.swing.JTextField();
        ShowReloj = new javax.swing.JButton();
        ShowAlarma = new javax.swing.JButton();
        Visualizador = new javax.swing.JTextField();
        ON_alarma = new javax.swing.JButton();
        OFF_alarma = new javax.swing.JButton();
        Add_Hours = new javax.swing.JButton();
        Add_min = new javax.swing.JButton();
        encendido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TFmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFmostrarActionPerformed(evt);
            }
        });

        ShowReloj.setText("Mostrar Reloj");
        ShowReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRelojActionPerformed(evt);
            }
        });

        ShowAlarma.setText("Mostrar Alarma");
        ShowAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAlarmaActionPerformed(evt);
            }
        });

        Visualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizadorActionPerformed(evt);
            }
        });

        ON_alarma.setText("Encender Alarma");
        ON_alarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ON_alarmaActionPerformed(evt);
            }
        });

        OFF_alarma.setText("Apagar Alarma");
        OFF_alarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFF_alarmaActionPerformed(evt);
            }
        });

        Add_Hours.setText("+ Horas");
        Add_Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_HoursActionPerformed(evt);
            }
        });

        Add_min.setText("+ Minutos");
        Add_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_minActionPerformed(evt);
            }
        });

        encendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encendidoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/relojalarma/reloj.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 337, Short.MAX_VALUE)
                        .addComponent(Visualizador, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowReloj, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(Add_Hours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ON_alarma)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ShowAlarma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OFF_alarma)
                                    .addComponent(Add_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(encendido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowReloj)
                    .addComponent(ShowAlarma))
                .addGap(24, 24, 24)
                .addComponent(TFmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add_Hours)
                            .addComponent(Add_min))
                        .addGap(11, 11, 11)
                        .addComponent(Visualizador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ON_alarma)
                            .addComponent(OFF_alarma))
                        .addGap(23, 23, 23)
                        .addComponent(encendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRelojActionPerformed
        // TODO add your handling code here:
        reloj_alarma=true;
        TFmostrar.setText("Reloj");
        
    }//GEN-LAST:event_ShowRelojActionPerformed

    private void TFmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFmostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFmostrarActionPerformed

    private void ShowAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAlarmaActionPerformed
        // TODO add your handling code here:
        Alarma alarma;
        reloj_alarma=false;
        TFmostrar.setText("Alarma");
        reloj_alarma=false;
        if(Alarma.encendido==false)
            alarma=new Alarma();
        
    }//GEN-LAST:event_ShowAlarmaActionPerformed

    private void VisualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizadorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VisualizadorActionPerformed

    private void ON_alarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ON_alarmaActionPerformed
        // TODO add your handling code here:
        Alarma.encendido=true;
        this.encendido.setText("Alarma ENCENDIDA");
    }//GEN-LAST:event_ON_alarmaActionPerformed

    private void OFF_alarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFF_alarmaActionPerformed
        // TODO add your handling code here:
        Alarma.encendido=false;
        this.encendido.setText("Alarma APAGADA");
    }//GEN-LAST:event_OFF_alarmaActionPerformed

    private void Add_HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_HoursActionPerformed
        // TODO add your handling code here:
        incrementarHoras();
    }//GEN-LAST:event_Add_HoursActionPerformed

    private void Add_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_minActionPerformed
        // TODO add your handling code here:
        incrementarMinutos();
    }//GEN-LAST:event_Add_minActionPerformed

    private void encendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encendidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    public static void mostrarHora(){
        Visualizador.setText(Reloj.HCompleta);
    }
    
    public static void mostrarAlarma(){
        Visualizador.setText(Alarma.getHCompleta());
    }
    
    public static void incrementarHoras(){
        if(reloj_alarma==true)
            Reloj.sumarH();
        else
            Alarma.sumarH();
    }
     public static void incrementarMinutos(){
        if(reloj_alarma==true)
            Reloj.sumarMin();
        else
            Alarma.sumarMin();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Hours;
    private javax.swing.JButton Add_min;
    private javax.swing.JButton OFF_alarma;
    private javax.swing.JButton ON_alarma;
    private javax.swing.JButton ShowAlarma;
    private javax.swing.JButton ShowReloj;
    private javax.swing.JTextField TFmostrar;
    private static javax.swing.JTextField Visualizador;
    private javax.swing.JTextField encendido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
